# Generated by Django 6.1 on 2026-08-26 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('especificaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_por_hora', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SesionUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_solicitado_minutos', models.PositiveIntegerField(help_text='0 si es tiempo libre o fraccionado')),
                ('pagado', models.BooleanField(default=False)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('computadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocio.computadora')),
            ],
        ),
    ]
