# Generated by Django 6.1 on 2026-09-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('shooter', 'Shooter / FPS'), ('moba', 'MOBA'), ('carreras', 'Carreras'), ('deportes', 'Deportes'), ('estrategia', 'Estrategia')], default='shooter', max_length=30)),
                ('requiere_cuenta_propia', models.BooleanField(default=False)),
                ('computadoras', models.ManyToManyField(blank=True, related_name='juegos', to='negocio.computadora')),
            ],
        ),
    ]
